### PR TITLE
Update package config for rstan compatibility

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates your packages installation/configuration to delegate to `rstantools` for compatibility with the upcoming rstan version

### CODE REVIEW

**Comment by andrjohns** [comment]
Would you be able to submit a new release to CRAN with this merged PR when you can? Thanks

**Comment by sujit-sahu** [comment]
Dear Andrew,
 Thanks for your email.  Yes, the patch works with the latest versions of the stan packages. But I am travelling now and I can only try to upload to CRAN after March 26th   from my desktop in Southampton. I hope it is possible to wait until then.
Best wishes, Sujit


From: Andrew Johnson ***@***.***>
Date: Saturday, 11 March 2023 at 16:16
To: sujit-sahu/bmstdr ***@***.***>
Cc: Sujit Sahu ***@***.***>, State change ***@***.***>
Subject: Re: [sujit-sahu/bmstdr] Update package config for rstan compatibility (PR #16)
CAUTION: This e-mail originated outside the University of Southampton.

Would you be able to submit a new release to CRAN with this merged PR when you can? Thanks

**Comment by andrjohns** [comment]
Of course, not an issue at all. Thanks!

**Comment by andrjohns** [comment]
Apologies for the double-ping, but would you be able to make the submission to CRAN soon? Thanks!

**Comment by sujit-sahu** [comment]
Hi Andrew,
 Just to confirm that a new version of the package has made it to CRAN over the weekend.
Thank you for your help.
Best wishes, Sujit

From: Andrew Johnson ***@***.***>
Date: Tuesday, 28 March 2023 at 09:49
To: sujit-sahu/bmstdr ***@***.***>
Cc: Sujit Sahu ***@***.***>, State change ***@***.***>
Subject: Re: [sujit-sahu/bmstdr] Update package config for rstan compatibility (PR #16)
CAUTION: This e-mail originated outside the University of Southampton.

Apologies for the double-ping, but would you be able to make the submission to CRAN soon? Thanks!

**Comment by andrjohns** [comment]
Great news, thanks!

**Pull request merged**
